import { canAccessNavItem } from "../utils/rbac";

const modules = [
  {
    key: "getting-started",
    title: "Getting Started",
    summary: "Core navigation, permissions, notifications, and personal setup.",
    articles: [
      article("welcome-to-syntask", "Welcome to SynTask", null, "SynTask is a company workspace for work, sales, people operations, finance, reporting, and AI assistance. Your sidebar shows the areas your role and module access allow you to use.", "All authenticated users.", "Sidebar -> Home", ["Sign in with an active SynTask account."], ["Open SynTask and review the sidebar.", "Use Home to see your current work and important summaries.", "Open the section that matches the work you need to do.", "Use Settings to manage your profile."], "You can work from the modules visible to you without needing outside documentation.", ["If a module is missing, your role or module access may not include it.", "After an admin changes access, refresh or wait for SynTask to sync your permissions."], ["Open the SOP Library", "Understand Roles and Permissions"]),
      article("open-the-sop-library", "Open the SOP Library", null, "The SOP Library is the in-app user manual for SynTask. It is available to every authenticated user, even when other modules are hidden.", "All authenticated users.", "Sidebar -> SOP Library", ["You must be signed in."], ["Click SOP Library in the sidebar.", "Browse a module category or use Search SOPs.", "Select an article to read the steps.", "Use related SOP links to continue learning."], "The SOP Library page opens without changing your access to any other module.", ["If a direct article link is wrong, SynTask shows a safe not found message.", "Search may return no results when the term does not match a current SOP."], ["Welcome to SynTask", "Understand Roles and Permissions"]),
      article("understand-roles-and-permissions", "Understand Roles and Permissions", null, "SynTask uses roles, module access, department access, and record ownership to decide what each user can see and do. Reading an SOP does not grant access to the feature it describes.", "All authenticated users.", "Sidebar -> SOP Library", ["You need an active user account."], ["Open SOP Library.", "Search for the module you want to understand.", "Read the Who Can Use It section in the article.", "Ask an admin or manager if you need access to a hidden module."], "You understand which features are visible to your account and why some features may be hidden.", ["Module access and action permission are different. You may see a module but still be unable to create, edit, delete, or approve records.", "Project Leads may receive extra permissions only inside assigned projects."], ["Manage Member Permissions", "Understand Project Lead Permissions"]),
      article("use-notifications", "Use Notifications", "Notifications", "Notifications collect important SynTask updates such as scheduled work, reminders, and activity notices.", "All authenticated users.", "Sidebar -> Inbox -> Notifications", ["You must be signed in."], ["Open Notifications from the Inbox section.", "Review unread and recent updates.", "Open a notification to go to the related work when a link is available.", "Clear or revisit notifications as needed."], "You stay informed about work that needs your attention.", ["Some notifications depend on background jobs and may arrive after a short delay.", "If a record is not accessible, the notification will not override permissions."], ["View Calendar", "Manage Scheduled Work"]),
    ],
  },
  {
    key: "dashboard",
    title: "Home and Dashboard",
    summary: "Use Home to scan current workspace activity and jump into work.",
    navItem: { name: "Home", href: "/dashboard" },
    articles: [
      article("use-home-dashboard", "Use the Home Dashboard", "Home", "Home is the main landing page after sign-in. It summarizes workspace activity and gives quick access to the work you can use.", "All authenticated users. Super Admin users are redirected to the Super Admin dashboard.", "Sidebar -> Home", ["You must be signed in."], ["Click Home in the sidebar.", "Review the summary cards and visible workspace sections.", "Open a linked item to continue work in its module.", "Use section tabs or the sidebar to move to related areas."], "You can quickly find high-priority work and module summaries.", ["Dashboard content depends on your role, modules, and available data.", "Empty sections usually mean no current records for your account."], ["How to Find Your Work", "View Workspace Reports"]),
      article("find-your-work", "How to Find Your Work", "Home", "SynTask shows work through Home, Tasks, Projects, Calendar, Notifications, and module-specific lists. The best starting point depends on the type of work you need.", "All authenticated users.", "Sidebar -> Home", ["You must have access to the module that owns the work."], ["Open Home for a high-level view.", "Open Tasks for assigned task work.", "Open Projects for project boards.", "Open Calendar for dated work and follow-ups.", "Open Notifications for recent updates."], "You can move from a summary to the record that needs action.", ["If a linked record is no longer available, it may have been deleted or your access may have changed."], ["Use the Home Dashboard", "View Calendar", "Use Notifications"]),
    ],
  },
  {
    key: "work",
    title: "Work",
    summary: "Projects, tasks, requests, scheduled work, time tracking, and daily updates.",
    navItem: { name: "Projects", href: "/projects", module: "tasks_projects" },
    articles: [
      article("project-overview", "Project Overview", "Projects", "Projects organize delivery work. A project can have a client, type, dates, members, a manager, a project lead, tasks, files, pages, board columns, epics, and sprints.", "Users with Work access. Create and management actions depend on role and project permissions.", "Sidebar -> Work -> Projects", ["You need Work access to open Projects."], ["Open Projects.", "Review the project list or cards.", "Open a project to view its board.", "Use board and task views to manage delivery work."], "You can see the projects your account is allowed to access.", ["Not every user can create, edit, assign, or delete projects.", "Scheduled project placeholders are visible to the scheduling user before publish."], ["Create a Project", "Assign a Project Lead", "Create a Task"]),
      article("create-project", "Create a Project", "Projects", "Create a project when a new delivery workspace is needed. SynTask supports immediate creation and scheduled project creation.", "Admin, Sub Admin, Manager, and other roles allowed by project creation rules.", "Sidebar -> Work -> Projects", ["You need permission to create projects.", "Prepare the project name and any client, type, dates, manager, lead, and team details."], ["Open Projects.", "Click New project.", "Enter the project details.", "Select an existing client or create a client if you have permission.", "Choose members, manager, and project lead where needed.", "Leave scheduling off to create now, or turn it on and choose the publish time.", "Click Create project or Schedule project."], "The project appears in Projects. Scheduled projects appear as placeholders until the publish time.", ["Missing required fields block creation.", "You may be unable to create clients or users from the form if your role cannot create them."], ["Project Overview", "Assign Project Members", "Manage Scheduled Work"]),
      article("edit-project", "Edit a Project", "Projects", "Project edits update project details such as status, dates, ownership, and metadata where your role allows it.", "Project managers, admins, or users with manage permission for the project.", "Sidebar -> Work -> Projects", ["You must be allowed to manage the selected project."], ["Open Projects.", "Find the project.", "Use the project actions menu or Edit action.", "Update the allowed fields.", "Click Save changes."], "The project list and board use the updated project information.", ["The Edit action is hidden when you do not have manage permission.", "Server validation may reject incomplete or invalid values."], ["Create a Project", "Assign Project Lead"]),
      article("assign-project-members", "Assign Project Members", "Projects", "Project members define who can participate in a project and see project work.", "Admins, managers, and permitted project managers or leads.", "Sidebar -> Work -> Projects", ["The project must already exist.", "The employee must exist in SynTask."], ["Open Projects.", "Open the project assignment action.", "Select the employees who should work on the project.", "Save the assignment."], "Selected members gain access according to project and role rules.", ["Adding a member does not automatically make them the project lead.", "If an employee is missing, create the user first if your role allows it."], ["Assign a Project Lead", "Understand Project Lead Permissions"]),
      article("assign-project-lead", "Assign a Project Lead", "Projects", "A project lead coordinates work inside one project. An Employee can be a project lead for that project without becoming a global Lead.", "Company Admins and Managers, with project rules enforced by SynTask.", "Sidebar -> Work -> Projects", ["The project and selected employee must already exist."], ["Open Projects.", "Choose the project assignment action.", "Select the Project Lead.", "Click Save assignment."], "The selected person receives project-scoped lead permissions for that project.", ["Replacing or clearing the lead removes those project-scoped permissions.", "Project lead access does not apply to unrelated projects."], ["Understand Project Lead Permissions", "Create Project Tasks"]),
      article("understand-project-lead-permissions", "Understand Project Lead Permissions", "Projects", "Project Lead permissions are limited to the assigned project. They help a project lead view project work, create and schedule tasks, manage assignment, and coordinate delivery.", "Assigned project leads, managers, and admins.", "Sidebar -> Work -> Projects", ["A project must have a lead assigned."], ["Open Projects.", "Open the assigned project board.", "Use permitted task and board actions inside that project.", "Avoid assuming the same permissions apply outside the project."], "Project leads can help run their project without receiving broad admin access.", ["Old leads lose access after replacement.", "Regular project members do not get lead-only actions."], ["Assign a Project Lead", "Create a Task"]),
      article("create-task", "Create a Task", "Tasks", "Tasks track individual work items. Tasks can be created immediately or scheduled for later creation.", "Admins, managers, leads, and project leads where allowed.", "Sidebar -> Work -> Tasks", ["You need Work access.", "Prepare title, assignee, priority, dates, and optional project/department details."], ["Open Tasks.", "Click Create Task.", "Enter the task details.", "Select the assignee and related project or department if needed.", "Leave scheduling off to create now, or enable scheduling and choose a publish time.", "Click Create Task or Schedule Task."], "The task appears in the task list, or a scheduled task placeholder is created until publish time.", ["Follow-up tasks created from Sales are hidden from the standalone task list.", "Employees may see only tasks they are allowed to access."], ["Edit a Task", "Change Task Status", "Manage Scheduled Work"]),
      article("edit-task", "Edit a Task", "Tasks", "Task editing keeps the task record current as work changes.", "Users with task management permission for the task.", "Sidebar -> Work -> Tasks", ["The task must exist and be accessible to you."], ["Open Tasks.", "Open the task or use the edit action.", "Update the allowed fields.", "Click Save changes."], "The task updates across lists, boards, calendars, and reports that use it.", ["You may not be able to edit a task you can only view.", "Required fields and valid dates are checked when saving."], ["Create a Task", "Delete a Task"]),
      article("change-task-status", "Change Task Status", "Tasks", "Task status shows where work stands. Status changes help teams track progress.", "Users with access to update the task.", "Sidebar -> Work -> Tasks or Work -> Projects -> Project Board", ["The task must be accessible to you."], ["Open Tasks or a project board.", "Find the task.", "Change the status from the task card, board column, or task detail page.", "Save or wait for the change to complete."], "The task moves to the new status and related views update.", ["Some status changes may be blocked by permissions.", "A failed update leaves the task in its previous state."], ["Edit a Task", "Use Project Board"]),
      article("task-detail", "Use Task Detail", "Tasks", "Task Detail is the full task workspace. It includes metadata, comments, subtasks, attachments, time logs, watchers, and history where available.", "Users who can open the task.", "Sidebar -> Work -> Tasks -> select a task", ["The task must be visible to your account."], ["Open a task from Tasks or a project board.", "Review details, status, assignee, due date, and activity.", "Add comments, attachments, watchers, subtasks, or time logs where available.", "Return to the list or board when done."], "The full context for the task is available in one place.", ["Some panels may be empty when the task has no related records.", "Permissions decide which actions are editable."], ["Create a Task", "Log Time"]),
      article("delete-task", "Delete a Task", "Tasks", "Deleting a task removes it from active work views.", "Users with delete permission for the task.", "Sidebar -> Work -> Tasks", ["Confirm the task is no longer needed."], ["Open Tasks.", "Find the task.", "Click Delete.", "Confirm the deletion."], "The task is removed from task views.", ["Deletion is not available for every role.", "Do not delete follow-up tasks unless the related Sales follow-up should be removed through its own flow."], ["Create a Task", "Task Detail"]),
      article("manage-scheduled-work", "Manage Scheduled Work", "Scheduled Work", "Scheduled Work shows project and task creation jobs that publish later.", "Managers, leads, admins, and users who scheduled work according to route access.", "Sidebar -> Work -> Scheduled Work", ["A project or task must have been scheduled."], ["Open Scheduled Work.", "Review pending, completed, failed, or cancelled jobs.", "Open related records after they publish.", "Cancel or retry only when your role allows it."], "You can track future work creation and see whether it completed.", ["Scheduled jobs run in the background and may take a short time to appear.", "Only authorized users can manage scheduled jobs."], ["Create a Project", "Create a Task"]),
      article("log-time", "Log Time and View Timesheets", "Time Tracking", "SynTask supports task time logging through Time Tracking, Timesheet, and task detail time panels.", "Users with Work access.", "Sidebar -> Work -> Time Tracking or Work -> Time Tracking", ["You need a task or work item to log time against."], ["Open Time Tracking or Timesheet.", "Start, stop, or add a time entry where available.", "Review entries and summaries.", "Use task detail to inspect time tied to a specific task."], "Time entries appear in timesheet views and related task context.", ["Time Tracking and Timesheet are separate views and may show different levels of detail.", "Some reporting views are manager-focused."], ["Task Detail", "View Workspace Reports"]),
      article("submit-daily-update", "Submit Daily Updates", "Daily Updates", "Daily Updates are end-of-day reports used to summarize work, blockers, and progress.", "All standard roles with access to Daily Updates.", "Sidebar -> People or Work -> Daily Updates", ["You must be signed in."], ["Open Daily Updates.", "Review existing updates.", "Create or edit your update where allowed.", "Submit the report."], "Managers and authorized users can review work updates.", ["Late or missing updates may affect reporting.", "Visibility depends on hierarchy and role."], ["Use Home Dashboard", "View Workspace Reports"]),
      article("use-requests", "Use Requests", "Requests", "Requests are ticket-style work items for support or internal asks.", "Users with Requests access.", "Sidebar -> Work -> Requests", ["You must have access to Requests."], ["Open Requests.", "Review the ticket list.", "Create or open a request.", "Update status or details where allowed."], "Requests are tracked separately from normal project tasks.", ["Requests use their own module permission.", "Managers, leads, and employees are auto-granted request access in the current backend rules."], ["Use Notifications", "View Workspace Reports"]),
    ],
  },
  {
    key: "calendar",
    title: "Calendar",
    summary: "Workspace calendar for dated tasks, scheduled work, follow-ups, and events.",
    navItem: { name: "Calendar", href: "/calendar" },
    articles: [
      article("view-calendar", "View Calendar", "Calendar", "Calendar helps users see dated workspace items in one place. It includes task and scheduled-work style events according to the current app data.", "All authenticated users.", "Sidebar -> Home -> Calendar", ["You must be signed in."], ["Open Calendar.", "Review items by date.", "Use filters or view controls when available.", "Open a linked item to continue work."], "You can see date-based work you are allowed to access.", ["Only accessible records appear.", "Some CRM calendar behavior lives under Clients -> Client Calendar."], ["View Tasks in Calendar", "View Follow-Ups in Calendar"]),
      article("view-tasks-in-calendar", "View Tasks in Calendar", "Calendar", "Tasks with due dates can appear in calendar views so users can plan work by date.", "Users who can access the task.", "Sidebar -> Home -> Calendar", ["Tasks must have a due date or creation date fallback."], ["Open Calendar.", "Find the task date.", "Select the task event.", "Open the task detail if a link is available."], "The task opens or shows enough context to plan the work.", ["Missing due dates can make tasks harder to find in calendar views.", "Calendar access does not bypass task permissions."], ["Create a Task", "Task Detail"]),
      article("view-followups-in-calendar", "View Follow-Ups in Calendar", "Calendar", "Sales follow-ups are scheduled from leads and can be reviewed through calendar-style views.", "Users with Sales access to the related lead.", "Sidebar -> Clients -> Client Calendar or Home -> Calendar where available", ["The follow-up must be scheduled on a lead."], ["Open the calendar view.", "Filter or scan for follow-up items.", "Open the related lead or activity.", "Complete, reschedule, or cancel the follow-up from the Sales flow where available."], "Follow-up commitments are visible alongside other dated work.", ["If you cannot access the lead, you cannot use the follow-up link.", "Standalone Tasks hides Sales follow-up tasks to keep task lists focused."], ["Schedule a Lead Follow-Up", "Sales Workflow"]),
    ],
  },
  {
    key: "attendance",
    title: "Attendance and People Operations",
    summary: "Attendance, live monitoring, reports, leave, employees, departments, and permissions.",
    navItem: { name: "Attendance", href: "/attendance" },
    articles: [
      article("check-in", "Check In", "Attendance", "Check In starts your attendance record for the day.", "All authenticated users.", "Sidebar -> People -> Attendance", ["You must not already be checked in for the active day."], ["Open Attendance.", "Click Check In.", "Wait for the status to update."], "Your attendance status changes to working and the check-in time appears.", ["If Check In is unavailable, you may already be checked in or the request failed.", "Refresh if the status does not update."], ["Start Break", "Check Out"]),
      article("start-break", "Start Break", "Attendance", "Start Break records that you are temporarily away during a checked-in workday.", "Checked-in users.", "Sidebar -> People -> Attendance", ["You must be checked in."], ["Open Attendance.", "Click Start Break.", "Wait for the status to update."], "Your status changes to on break.", ["You cannot start a break before checking in.", "Use End Break before checking out if the UI requires it."], ["End Break", "Check Out"]),
      article("end-break", "End Break", "Attendance", "End Break returns your status from break to working.", "Users currently on break.", "Sidebar -> People -> Attendance", ["You must have started a break."], ["Open Attendance.", "Click End Break when shown.", "Wait for the status to update."], "Your attendance status returns to working.", ["If End Break is not shown, your current status may not be on break."], ["Start Break", "Check Out"]),
      article("check-out", "Check Out", "Attendance", "Check Out closes your attendance for the day.", "Checked-in users.", "Sidebar -> People -> Attendance", ["You must be checked in."], ["Open Attendance.", "Click Check Out.", "Confirm if prompted."], "Your attendance status changes to checked out and the day record is completed.", ["Checking out may be blocked while a break is active.", "If the action fails, check your connection and try again."], ["Check In", "View Attendance History"]),
      article("view-attendance-history", "View Attendance History", "Attendance", "Attendance history shows previous check-ins, breaks, check-outs, and daily attendance records.", "All authenticated users for their own records; managers and admins may see broader reports.", "Sidebar -> People -> Attendance", ["You need attendance records to review."], ["Open Attendance.", "Scroll to the history section.", "Review dates, check-in, break, and check-out values."], "You can verify your attendance activity.", ["No history appears when no records exist for the selected range."], ["View Attendance Reports", "Use Live Attendance"]),
      article("use-live-attendance", "Use Live Attendance", "Live Attendance", "Live Attendance helps team leads and managers monitor current working, break, and offline statuses.", "Team leads, managers, admins, and roles allowed by the sidebar.", "Sidebar -> People -> Live Attendance", ["You need permission to view live team attendance."], ["Open Live Attendance.", "Review current employee statuses.", "Use filters if available.", "Follow up outside SynTask if attention is needed."], "Authorized users can see current attendance state for permitted employees.", ["Live data can lag briefly.", "Live monitoring does not replace attendance reports."], ["View Attendance Reports", "Check In"]),
      article("view-attendance-reports", "View Attendance Reports", "Attendance Reports", "Attendance Reports provide filtered attendance metrics and export-style reporting.", "All standard roles can open the page; broader team visibility depends on role and backend rules.", "Sidebar -> People -> Attendance Reports", ["Attendance records must exist for the selected period."], ["Open Attendance Reports.", "Choose filters or date range if available.", "Review metrics and records.", "Export where the page provides export controls."], "You can review attendance patterns for your permitted scope.", ["No data appears when the selected period has no records.", "Report access does not grant access to other users outside your allowed scope."], ["View Attendance History", "Use Live Attendance"]),
      article("manage-leave", "Manage Leave", "Leave Management", "Leave Management tracks leave requests and approvals.", "All standard roles can access leave; approval scope depends on role and hierarchy.", "Sidebar -> People -> Leave Management", ["You must be signed in."], ["Open Leave Management.", "Create or review leave records.", "Submit, approve, reject, or update records where your role allows it."], "Leave status is tracked in SynTask.", ["Employees may only manage their own requests.", "Managers and admins may see team or company requests depending on access."], ["Use Home Dashboard", "View Workspace Reports"]),
      article("manage-employees", "Manage Employees", "Employees", "Employees is the company user management area for creating, editing, and reviewing user accounts.", "Admins, managers, leads, and roles allowed by the People section.", "Sidebar -> People -> Employees", ["You must have permission to manage or view employees."], ["Open Employees.", "Review the employee list.", "Create or edit employees where allowed.", "Assign roles, departments, managers, or modules according to your permissions."], "Employee records stay current and access can be controlled.", ["Not all users can create employees.", "Access changes may require the affected user to refresh or wait for permission sync."], ["Manage Member Permissions", "Manage Departments"]),
      article("manage-member-permissions", "Manage Member Permissions", "Roles & Permissions", "Member permissions control what modules and actions a user can use. Role defaults, module access, capabilities, department, hierarchy, and record ownership work together.", "Company Admin, Sub Admin, Super Admin, and authorized permission managers.", "Sidebar -> Settings -> Roles & Permissions", ["The target user must belong to your company or permitted scope."], ["Open Roles & Permissions.", "Find the member or department.", "Review role defaults and individual module access.", "Turn modules on or off according to the user's job.", "Save changes and ask the user to refresh if needed."], "The user's sidebar and route access update without granting unrelated permissions.", ["Module access lets a user enter a module; action permissions still decide create, edit, delete, approve, or admin actions.", "Never grant modules only to make an SOP visible. SOP Library is already visible to everyone."], ["Understand Roles and Permissions", "Manage Employees"]),
      article("manage-departments", "Manage Departments", "Departments", "Departments organize people and permission views.", "Super Admin, Admin, Sub Admin, Manager, and Lead roles according to current sidebar rules.", "Sidebar -> People -> Departments", ["You need permission to view departments."], ["Open Departments.", "Review department records.", "Create, edit, or inspect department details where available.", "Use department links in permission views when needed."], "Teams and permissions can be organized by department.", ["Department access may be hidden for employees.", "Department changes can affect permission and reporting views."], ["Manage Member Permissions", "Manage Employees"]),
    ],
  },
  {
    key: "sales",
    title: "Sales",
    summary: "Lead acquisition, qualification, pipeline movement, follow-ups, and sales reporting.",
    navItem: { name: "Leads", href: "/crm/leads", module: "sales_crm" },
    articles: [
      article("sales-workflow", "Sales Workflow", "Leads", "Sales is where active leads move through the pipeline. The current guided stages are Acquire, Qualify, Discovery, Proposal, Negotiation, Agreement, Won, and Lost.", "Users with Sales access.", "Sidebar -> Sales", ["Sales access is required."], ["Open Sales.", "Add or import leads.", "Move leads through the guided stages.", "Complete any missing details shown by SynTask before moving forward.", "Schedule follow-ups and record activities.", "Use Won for successful leads and Lost for unsuccessful leads."], "The sales team can track each lead from first contact through outcome.", ["Sales and Clients are separate: a lead remains in Sales until it is converted or handed off after the sales process.", "Some older Sales routes still redirect to CRM workspaces."], ["When Does a Lead Become a Client?", "Move a Lead to the Next Stage"]),
      article("add-lead", "Add a Lead", "Leads", "A lead is a potential customer or deal that is still in the sales process.", "Users with Sales access.", "Sidebar -> Sales -> Leads or Sales -> Pipeline", ["Prepare lead name, company/contact details, owner, source, stage, and deal details where available."], ["Open Leads or Pipeline.", "Click Add Lead.", "Enter the lead details.", "Select stage, owner, and other fields shown in the form.", "Save the lead."], "The lead appears in the lead list and pipeline.", ["Missing required fields prevent saving.", "Lead terminology is used in the current UI; older backend names may still say prospect in some places but users should follow the Lead UI."], ["Import Leads", "Sales Workflow"]),
      article("import-leads", "Import Leads", "Import Leads", "Import Leads supports bulk lead creation from a file or import workflow.", "Users with Sales access through the sidebar.", "Sidebar -> Sales -> Import Leads", ["Prepare lead data in the supported format shown by the page."], ["Open Import Leads.", "Choose the file or import source.", "Review mappings and validation messages.", "Start the import.", "Fix any rejected rows if the page reports issues."], "Valid leads are added to Sales.", ["Bulk imports can fail for missing or invalid fields.", "Imported leads still follow normal Sales permissions."], ["Add a Lead", "Sales Workflow"]),
      article("move-lead-stage", "Move a Lead to the Next Stage", "Pipeline", "The pipeline moves leads through the guided sales journey. SynTask can block movement when required stage details are missing.", "Users with Sales access and permission to update the lead.", "Sidebar -> Sales -> Pipeline", ["The lead must exist and be visible to you."], ["Open Pipeline.", "Drag the lead card or use the stage move action.", "If SynTask opens Additional information is required, fill in the missing fields.", "Click Save Details to keep the lead in the current stage, or Save and Move Forward to save and retry the move."], "The lead moves only when required stage information is complete.", ["Qualification, budget, decision maker, or other stage requirements may be required depending on the target stage.", "If Save and Move Forward fails, review the remaining missing fields."], ["Sales Workflow", "Schedule a Lead Follow-Up"]),
      article("schedule-follow-up", "Schedule a Lead Follow-Up", "Pipeline", "Follow-ups turn a sales commitment into a dated reminder and task-style item.", "Users with Sales access to the lead.", "Sidebar -> Sales -> Pipeline", ["The lead must exist.", "The follow-up date and time must be in the future."], ["Open Pipeline.", "Find the lead.", "Choose Schedule Follow-up.", "Enter the follow-up title.", "Choose Follow-up date & time.", "Add notes or reminder details if shown.", "Click Schedule Follow-up."], "SynTask creates the follow-up and reminds the responsible user.", ["The dialog rejects missing or past dates.", "Use Reschedule Follow-up to change an existing follow-up."], ["View Follow-Ups in Calendar", "Move a Lead to the Next Stage"]),
      article("reschedule-cancel-follow-up", "Reschedule or Cancel a Follow-Up", "Pipeline", "Follow-ups can be changed when a call, meeting, or next step changes.", "Users with access to the related lead and follow-up.", "Sidebar -> Sales -> Pipeline", ["The follow-up must already exist."], ["Open the lead or pipeline item.", "Open the follow-up dialog.", "Change the date and click Reschedule, or click Cancel Follow-up.", "Confirm the action if prompted."], "The reminder is updated or removed.", ["Cancelled follow-ups should not be treated as completed work.", "Past follow-up times are not accepted when scheduling."], ["Schedule a Lead Follow-Up", "View Follow-Ups in Calendar"]),
      article("lead-workspace", "Use the Lead Workspace", "Leads", "The Lead Workspace shows one lead's summary, timeline, notes, files, deal information, proposals, documents, stage history, and related context.", "Users with Sales access to the lead.", "Sidebar -> Sales -> Leads -> select a lead", ["The lead must be visible to your account."], ["Open Leads or Pipeline.", "Select a lead.", "Use the workspace tabs to review timeline, notes, files, documents, and history.", "Add notes or files where available.", "Return to Pipeline to manage stage movement."], "You have a single place to understand and work the lead.", ["Some tabs are functional foundations or read-only depending on available data.", "If access is denied, the lead may belong outside your allowed scope."], ["Add a Lead", "Move a Lead to the Next Stage"]),
      article("manage-lead-notes-files", "Manage Lead Notes and Files", "Leads", "Notes and files keep lead context attached to the lead record.", "Users with Sales access to the lead.", "Sidebar -> Sales -> Leads -> Lead Workspace", ["The lead must exist."], ["Open the Lead Workspace.", "Open Notes or Files.", "Add, edit, or delete notes and files where the page allows it.", "Review the timeline for related activity."], "Sales context stays connected to the lead.", ["File upload may reject unsafe or unsupported files.", "Deleting a note or file may be permanent."], ["Use the Lead Workspace", "Create CRM Documents"]),
      article("create-crm-documents", "Create CRM Documents", "Leads", "CRM documents support proposal and document workflows tied to leads. Public secure CRM document links also exist for sharing generated documents.", "Users with Sales access and document permissions for the lead.", "Sidebar -> Sales -> Leads -> Lead Workspace", ["The lead must exist.", "Required deal or proposal information must be available."], ["Open the Lead Workspace.", "Open Documents or Proposals.", "Create or preview the document where the page offers the action.", "Use secure share or download actions only when available."], "The document is tied to the lead and can be reviewed or shared through supported flows.", ["Some document lifecycle pieces are still partial; do not assume every proposal or contract action is available on every lead.", "Public links are access-controlled by token and do not expose normal app access."], ["Use the Lead Workspace", "When Does a Lead Become a Client?"]),
      article("when-lead-becomes-client", "When Does a Lead Become a Client?", "Leads", "Sales and Clients are separate domains. A lead stays in Sales while the sales process is active. Clients are for post-conversion customer management.", "Sales users, managers, admins, and anyone learning SynTask.", "Sidebar -> Sales and Sidebar -> Clients", ["A lead must complete the sales process before client handoff."], ["Work the lead in Sales.", "Move the lead through the final sales stages.", "Use Won or the available conversion/handoff flow when the customer becomes active.", "Manage the customer afterward from Clients or CRM Companies as appropriate."], "Active selling stays in Sales; post-conversion customer work moves to Clients.", ["Do not create duplicate client records just because a lead exists.", "If conversion controls are unavailable, follow your team's current handoff process."], ["Sales Workflow", "Manage Clients"]),
      article("view-sales-reports", "View Sales Reports", "Sales Reports", "Sales Reports show sales performance, prospect/lead activity, stage breakdowns, and related analytics.", "Users with Sales Reports access.", "Sidebar -> Insights -> Sales Reports", ["Sales data must exist for useful reporting."], ["Open Sales Reports.", "Choose filters if available.", "Review charts, tables, or export options.", "Open related leads when links are available."], "Sales leaders and users can review pipeline and performance signals.", ["Sales Reports and CRM Reports overlap in the current product.", "Report values depend on data quality in leads and stages."], ["Sales Workflow", "View CRM Reports"]),
      article("manage-sales-settings", "Manage Sales Settings", "Sales Settings", "Sales settings manage reusable sales values such as stages, tags, channels, categories, and products.", "Sales managers, admins, and CRM settings users according to current access rules.", "Sidebar -> Settings -> Client Settings or legacy Sales Settings where available", ["You need Sales settings access."], ["Open the settings area.", "Choose the configuration group.", "Add or edit values shown by the page.", "Save changes."], "New sales records can use the configured values.", ["Some CRM settings are local or partially implemented, so only rely on values that appear in active forms.", "Configuration changes may not emit full activity history."], ["Move a Lead to the Next Stage", "Add a Lead"]),
    ],
  },
  {
    key: "clients",
    title: "Clients",
    summary: "Post-conversion client records, companies, contacts, calendar, and client reporting.",
    navItem: { name: "All Clients", href: "/clients" },
    articles: [
      article("manage-clients", "Manage Clients", "All Clients", "Clients is for customers after the sales process. It is not a duplicate of active Sales leads.", "Company admins and users whose sidebar exposes Clients.", "Sidebar -> Clients", ["The customer should be a real client, not only an active lead."], ["Open Clients.", "Review the client list.", "Create or edit client details where your role allows it.", "Open client workspace links when available."], "Client records support post-conversion operations.", ["If the customer is still being sold to, keep them in Sales as a lead.", "Client access is more restricted than Sales in the current sidebar."], ["When Does a Lead Become a Client?", "Manage Companies"]),
      article("manage-companies", "Manage Companies", "Companies", "Companies stores CRM company records and related workspace context.", "Team roles with Sales/CRM access.", "Sidebar -> Clients -> Companies", ["The company must be within your permitted tenant scope."], ["Open Companies.", "Search or filter the company list.", "Create, edit, delete, or open a company where allowed.", "Use the company workspace to review related contacts and leads."], "Company information is available for CRM and client context.", ["Company and Client are related concepts but not always the same screen.", "Delete actions may be restricted or permanent."], ["Manage Contacts", "Manage Clients"]),
      article("manage-contacts", "Manage Contacts", "Contacts", "Contacts stores people related to companies and sales/customer work.", "Team roles with Sales/CRM access.", "Sidebar -> Clients -> Contacts", ["The contact should belong to your company scope."], ["Open Contacts.", "Search or review the list.", "Create or edit contact details where available.", "Open linked company or lead records when needed."], "Contact details are reusable across CRM workflows.", ["Legacy Sales Contacts and CRM Contacts overlap; use the visible Clients -> Contacts page for CRM contacts.", "Incomplete contact details can reduce search and reporting quality."], ["Manage Companies", "Use the Lead Workspace"]),
      article("view-client-calendar", "View Client Calendar", "Client Calendar", "Client Calendar shows CRM meetings, tasks, and activities in an agenda-style view.", "Team roles with Sales/CRM access.", "Sidebar -> Clients -> Client Calendar", ["There must be dated CRM work to review."], ["Open Client Calendar.", "Use filters for owner, type, or search if available.", "Open related records from agenda items."], "You can see customer-facing dated work in one place.", ["The current CRM calendar is list-first, not a full month/week/day grid.", "Only permitted records appear."], ["View Follow-Ups in Calendar", "Manage CRM Activities"]),
      article("view-crm-reports", "View CRM Reports", "Client Insights", "Client Insights and CRM Reports summarize pipeline, revenue, conversion, segments, and performance from CRM dashboard data.", "Team roles with Sales/CRM access.", "Sidebar -> Clients -> Client Insights", ["CRM data must exist."], ["Open Client Insights.", "Choose available filters.", "Review report cards and tables.", "Export CSV where provided."], "You can understand CRM and customer activity trends.", ["Some report filtering is client-side and depends on dashboard data.", "Reports may be empty when CRM records are incomplete."], ["View Sales Reports", "Manage Clients"]),
    ],
  },
  {
    key: "hr",
    title: "Recruitment",
    summary: "Hiring dashboard, jobs, applications, candidates, interviews, offers, and hiring reports.",
    navItem: { name: "Hiring Dashboard", href: "/hr/recruitment", module: "recruitment" },
    articles: [
      article("recruitment-workflow", "Recruitment Workflow", "Hiring Dashboard", "Recruitment supports job openings, applications, candidates, talent pool, interviews, offers, public careers pages, and reports.", "HR users, recruiters, managers, admins, and roles allowed by the People section.", "Sidebar -> People -> Hiring Dashboard", ["Recruitment access is required."], ["Open Hiring Dashboard.", "Create or review Job Openings.", "Review Applications.", "Manage Candidates and Talent Pool.", "Schedule Interviews.", "Create and track Offers."], "Hiring work can move from job posting through offer response.", ["Some advanced workflows are implemented as current foundations and may not cover every hiring policy.", "Candidate Interview Screen is a workflow screen, not a sidebar item."], ["Create a Job Opening", "Add or Review Candidates", "Create an Offer"]),
      article("create-job-opening", "Create a Job Opening", "Job Openings", "Job Openings are recruitment roles that can be created, published, archived, or duplicated.", "Recruitment users with job management permission.", "Sidebar -> People -> Job Openings", ["Prepare job title, department, description, and required details."], ["Open Job Openings.", "Click Create Job.", "Enter the job details.", "Save the job.", "Publish, archive, or duplicate the job if those actions are available and appropriate."], "The job appears in recruitment job lists and may be available to applicants when published.", ["Empty job fields can block saving.", "Archived jobs should not be used for active hiring."], ["Recruitment Workflow", "Use the Career Portal"]),
      article("review-applications", "Review Applications", "Applications", "Applications is the recruitment inbox for submitted applications.", "Recruitment users with access.", "Sidebar -> People -> Applications", ["A candidate must have applied or been added."], ["Open Applications.", "Review new entries.", "Open candidate details.", "Move candidates forward according to the current status controls."], "Applications can be triaged into candidate workflows.", ["Applications may be empty if no jobs are published or no candidates applied."], ["Add or Review Candidates", "Schedule Interviews"]),
      article("manage-candidates", "Add or Review Candidates", "Candidates", "Candidates keeps hiring profiles, notes, attachments, and status information.", "Recruitment users with candidate access.", "Sidebar -> People -> Candidates", ["The person should be part of a hiring process."], ["Open Candidates.", "Search or filter the candidate list.", "Open a candidate.", "Add notes or attachments where available.", "Update details or status according to the page controls."], "Candidate information is available for hiring decisions.", ["Resume parsing or scoring should only be documented when visible and working in your environment.", "Attachment upload may reject unsupported files."], ["Review Applications", "Use Talent Pool"]),
      article("use-talent-pool", "Use the Talent Pool", "Talent Pool", "The Talent Pool stores resumes or candidates for future hiring needs.", "Recruitment users with resume pool access.", "Sidebar -> People -> Talent Pool", ["Candidate or resume records must exist."], ["Open Talent Pool.", "Search or review available profiles.", "Open candidates that match a future role.", "Move or link them to current hiring work where available."], "Reusable candidate context is available without creating duplicate records.", ["Talent Pool is separate from active Applications.", "Some matching or scoring views may be informational only."], ["Add or Review Candidates", "Create a Job Opening"]),
      article("schedule-interviews", "Schedule Interviews", "Interviews", "Interviews tracks candidate interview events and interview workflow screens.", "Recruitment users with interview access.", "Sidebar -> People -> Interviews", ["The candidate should already exist."], ["Open Interviews.", "Create or open an interview record.", "Choose candidate, time, interviewer, and details shown by the form.", "Save the interview."], "The interview appears in the recruitment interview list.", ["Candidate Interview Screen is available as a workflow route but is hidden from normal sidebar navigation.", "Scheduling does not override interviewer availability outside SynTask."], ["Add or Review Candidates", "Create an Offer"]),
      article("create-offer", "Create an Offer", "Offers", "Offers supports offer drafts, PDF generation, sending, and secure candidate responses in the current recruitment module.", "Recruitment users with offer access.", "Sidebar -> People -> Offers", ["The candidate and joining date must be available for draft creation."], ["Open Offers.", "Select the candidate and joining date.", "Click Save draft.", "Generate, send, or track the offer response using the actions available on the page."], "The offer moves through draft, send, and response tracking where supported.", ["Offer actions may be blocked until required fields are present.", "Public offer links are token-scoped and do not grant app access."], ["Schedule Interviews", "Recruitment Workflow"]),
      article("use-career-portal", "Use the Career Portal", "Job Openings", "The public Career Portal lets candidates browse jobs, view job details, apply, and track applications without signing into SynTask.", "Candidates use public pages; recruiters manage jobs and applications inside SynTask.", "Public Careers pages and People -> Job Openings", ["A job must be published for candidates to apply."], ["Recruiters create and publish jobs.", "Candidates open the public careers page.", "Candidates apply from the job details page.", "Candidates track applications from the public tracking page."], "Public applicants can enter the recruitment workflow while internal users manage hiring in SynTask.", ["Public pages are intentionally separate from authenticated SynTask modules.", "Do not place private company data in public job descriptions."], ["Create a Job Opening", "Review Applications"]),
    ],
  },
  {
    key: "finance",
    title: "Finance",
    summary: "Invoices, transactions, subscriptions, and billing views.",
    navItem: { name: "Invoices", href: "/invoices", module: "invoicing_ledger" },
    articles: [
      article("manage-invoices", "Manage Invoices", "Invoices", "Invoices tracks customer billing documents and invoice PDFs.", "Company admins with Finance access.", "Sidebar -> Finance -> Invoices", ["You need Finance access and admin-level role."], ["Open Invoices.", "Review invoice records.", "Create or edit invoices where available.", "Generate or download PDFs when the page provides the action."], "Invoice records and documents are available for billing workflows.", ["Finance is hidden for non-admin users in the sidebar.", "Invoice behavior depends on valid client and billing data."], ["Manage Transactions", "Manage Clients"]),
      article("manage-transactions", "Manage Transactions", "Transactions", "Transactions tracks ledger-style income and expense records.", "Company admins with Finance access.", "Sidebar -> Finance -> Transactions", ["You need Finance access and admin-level role."], ["Open Transactions.", "Review ledger entries.", "Add or update entries where available.", "Use filters or summaries to inspect financial activity."], "Authorized users can review financial movement.", ["Transactions are separate from Sales pipeline values.", "Do not enter sensitive payment credentials in notes or descriptions."], ["Manage Invoices", "Manage Subscriptions"]),
      article("manage-subscriptions", "Manage Subscriptions", "Subscriptions", "Subscriptions shows plan and subscription information for the tenant.", "Company admins.", "Sidebar -> Finance -> Subscriptions", ["You need admin access."], ["Open Subscriptions.", "Review current plan and available options.", "Upgrade or manage subscription actions where available."], "Admins can understand subscription state and plan limits.", ["Subscription changes may require billing authorization outside the page.", "Super Admin has a separate platform billing workspace."], ["Manage Invoices", "Use Super Admin Workspace"]),
    ],
  },
  {
    key: "settings",
    title: "Settings and Integrations",
    summary: "Profile, permissions, workflow rules, Google Workspace, CRM settings, and activity logs.",
    navItem: { name: "System Settings", href: "/settings" },
    articles: [
      article("update-profile", "Update Profile", "System Settings", "System Settings includes the user's own settings and profile-style controls.", "All authenticated users.", "Sidebar -> Settings -> System Settings", ["You must be signed in."], ["Open System Settings.", "Update available profile fields.", "Save changes."], "Your profile settings update for your account.", ["Some settings are read-only for non-admin users.", "Avatar or account fields may require valid formats."], ["Understand Roles and Permissions"]),
      article("manage-automation-rules", "Manage Automation Rules", "Automation Rules", "Automation Rules is the workflow administration area for configured task/workflow automation.", "Company admins.", "Sidebar -> Settings -> Automation Rules", ["You need Company Admin access."], ["Open Automation Rules.", "Review existing workflows.", "Create or edit allowed automation rules.", "Save and monitor results."], "Automation rules can help standardize repeatable work.", ["Automation Rules is admin-gated.", "Do not change business workflows just to document them."], ["Manage Scheduled Work", "Use Notifications"]),
      article("connect-google-workspace", "Use Google Workspace", "Google Workspace", "Google Workspace is a native SynTask workspace for connected Google account status and related Google work features.", "All standard roles can open the page; connection capabilities depend on configuration.", "Sidebar -> Settings -> Google Workspace", ["Your company must have Google Workspace integration configured for useful connection flows."], ["Open Google Workspace.", "Review connection status.", "Connect or manage the account using visible page actions.", "Follow any consent prompts."], "Your Google Workspace connection status is visible in SynTask.", ["External consent or admin configuration may be required.", "Do not paste secrets into SynTask pages."], ["Update Profile", "Use Calendar"]),
      article("view-activity-logs", "View Activity Logs", "Activity Logs", "Activity Logs show material actions and system activity where the app records them.", "Super Admin, Admin, Sub Admin, and Lead roles according to current sidebar rules.", "Sidebar -> Settings -> Activity Logs", ["You need a role allowed to view activity logs."], ["Open Activity Logs.", "Filter or review recent actions.", "Open related records if links are provided."], "Authorized users can audit important activity.", ["Not every product action currently emits a full activity event.", "Activity visibility follows tenant and role scope."], ["Manage Member Permissions", "Use Notifications"]),
      article("manage-client-settings", "Manage Client Settings", "Client Settings", "Client Settings includes CRM settings and Meta messaging connection panels such as WhatsApp, Instagram, Messenger, identity, readiness, and analytics placeholders.", "Company admins and managers.", "Sidebar -> Settings -> Client Settings or Inbox/Publishing entries that open CRM settings panels", ["You need CRM settings access."], ["Open Client Settings.", "Choose the settings panel or use a sidebar shortcut such as WhatsApp or Messenger.", "Review connection status and readiness.", "Make changes only where the panel provides working controls."], "CRM and channel settings are visible for authorized users.", ["Some panels are marked Soon or readiness-only and should not be treated as fully live.", "Connected account changes may require external platform setup."], ["Manage Sales Settings", "Use Meta Messages"]),
    ],
  },
  {
    key: "ai",
    title: "AI Workspace and Content",
    summary: "AI Assistant, AI Content Assistant, Content Calendar, Content Studio, and Meta inbox helpers.",
    navItem: { name: "AI Assistant", href: "/ai-hub", module: "ai_agents" },
    articles: [
      article("use-ai-assistant", "Use AI Assistant", "AI Assistant", "AI Assistant provides SynTask AI help for authorized users. Current AI outputs should be treated as drafts, suggestions, or assistance unless the page clearly performs a saved action.", "Users with AI Workspace access.", "Sidebar -> AI Workspace -> AI Assistant", ["AI module access must be enabled."], ["Open AI Assistant.", "Choose the available assistant or conversation controls.", "Ask for help with permitted work.", "Review warnings, sources, or confidence details when shown before acting."], "You receive AI assistance without granting the assistant extra permissions beyond your account scope.", ["AI may be unavailable if provider configuration is missing.", "Do not paste secrets or private data that is not needed for the task."], ["Use Content Studio", "Use AI Content Assistant"]),
      article("use-ai-content-assistant", "Use AI Content Assistant", "AI Content Assistant", "AI Content Assistant supports marketing/content help inside the AI workspace.", "Users with AI Workspace access.", "Sidebar -> AI Workspace -> AI Content Assistant", ["AI module access must be enabled."], ["Open AI Content Assistant.", "Describe the content task.", "Review the generated draft.", "Edit before publishing or sharing."], "You get a content draft or suggestion.", ["AI drafts are not automatically approved business communication.", "Provider errors may prevent generation."], ["Use Content Calendar", "Use Content Studio"]),
      article("use-content-calendar", "Use Content Calendar", "Content Calendar", "Content Calendar organizes planned content work and is currently gated with the Work module.", "Users with Content Calendar access.", "Sidebar -> Content -> Content Calendar", ["You need Work module access."], ["Open Content Calendar.", "Review planned content items.", "Create or update items where the page allows it.", "Use linked work items to coordinate production."], "Content work is visible by date or plan.", ["Content Calendar is separate from Workspace Calendar.", "Access follows Work module permissions."], ["Use Content Studio", "View Calendar"]),
      article("use-content-studio", "Use Content Studio", "Content Studio", "Content Studio supports creative review and content generation workflows.", "Users with AI Workspace access.", "Sidebar -> Content -> Content Studio", ["AI module access is required."], ["Open Content Studio.", "Review creative inputs and suggestions.", "Use available scoring or generation controls.", "Save or act on outputs only after review."], "Creative support is available inside SynTask.", ["Some creative outputs are suggestions and need human review.", "Unsupported assets or missing context can reduce output quality."], ["Use AI Assistant", "Use Content Calendar"]),
      article("use-meta-messages", "Use Meta Messages", "Meta Messages", "Meta Messages brings supported Meta conversations into a CRM inbox with conversation lists, composer, identity linking, and AI draft helpers where configured.", "Users with Sales/CRM access; connection panels require manager/admin settings access.", "Sidebar -> Inbox -> Meta Messages", ["Meta integration must be configured for the channel."], ["Open Meta Messages.", "Select a conversation.", "Read the thread.", "Reply with the composer if the channel is connected.", "Use identity linking or AI draft panels where visible."], "Supported customer conversations can be handled from SynTask.", ["WhatsApp, Instagram, Messenger, and AI Replies shortcuts open settings panels for authorized managers/admins.", "Some Publishing or Approval Queue items are marked Soon."], ["Manage Client Settings", "Use AI Assistant"]),
    ],
  },
  {
    key: "reports",
    title: "Reports and Super Admin",
    summary: "Workspace reports, platform administration, subscriptions, usage, tenants, billing, and feature flags.",
    navItem: { name: "Workspace Reports", href: "/reports" },
    articles: [
      article("view-workspace-reports", "View Workspace Reports", "Workspace Reports", "Workspace Reports summarize operational data across permitted SynTask areas.", "All standard roles can open reports; data scope depends on role and backend rules.", "Sidebar -> Insights -> Workspace Reports", ["There must be records in the selected scope."], ["Open Workspace Reports.", "Choose filters if available.", "Review metrics and tables.", "Open related records when links are provided."], "You can review workspace performance for your allowed scope.", ["Empty reports often mean no records or no access to that data.", "Reports do not grant access to underlying records."], ["Use Home Dashboard", "View Sales Reports"]),
      article("use-super-admin-workspace", "Use Super Admin Workspace", "Super Admin", "The Super Admin workspace is separate from normal company workspaces. It manages tenants, plans, usage, billing, feature flags, companies, users, activity, and settings.", "Super Admin only.", "Super Admin routes under /super-admin", ["You must be signed in as Super Admin."], ["Open the Super Admin dashboard.", "Use Tenants to inspect subscribed clients.", "Use Plans, Usage, Billing, and Feature Flags for platform operations.", "Use tenant detail actions only for legitimate support or administration."], "Platform operations remain separate from tenant user workflows.", ["Super Admin access is not shown to normal company users.", "Cross-tenant content access must follow support policy and tenant isolation rules."], ["Manage Subscriptions", "View Activity Logs"]),
    ],
  },
];

function article(key, title, feature, overview, whoCanUse, whereToFind, beforeYouStart, steps, expectedResult, commonIssues, related = [], tips = []) {
  return {
    key,
    title,
    feature,
    overview,
    whoCanUse,
    whereToFind,
    beforeYouStart,
    steps,
    expectedResult,
    commonIssues,
    tips,
    related,
    screenshots: [],
  };
}

export const sopModules = modules;

export const sopArticles = modules.flatMap((module) =>
  module.articles.map((article) => ({
    ...article,
    moduleKey: module.key,
    moduleTitle: module.title,
    path: `/sop-library/${module.key}/${article.key}`,
  })),
);

export const getSopModule = (moduleKey) => modules.find((module) => module.key === moduleKey) || null;

export const getSopArticle = (moduleKey, articleKey) =>
  sopArticles.find((article) => article.moduleKey === moduleKey && article.key === articleKey) || null;

export const findRelatedArticle = (title) =>
  sopArticles.find((article) => article.title.toLowerCase() === String(title).toLowerCase()) || null;

export const canViewSopModule = (module, user) => {
  if (!module?.navItem) return true;
  return canAccessNavItem(user, module.navItem);
};

export const getVisibleSopModules = (user) =>
  modules.filter((module) => canViewSopModule(module, user));

export const getVisibleSopArticles = (user) =>
  getVisibleSopModules(user).flatMap((module) =>
    module.articles.map((article) => ({
      ...article,
      moduleKey: module.key,
      moduleTitle: module.title,
      path: `/sop-library/${module.key}/${article.key}`,
    })),
  );

export const searchSops = (query, user) => {
  const normalized = String(query || "").trim().toLowerCase();
  const articles = getVisibleSopArticles(user);
  if (!normalized) return articles;
  return articles.filter((article) => {
    const haystack = [
      article.title,
      article.feature,
      article.moduleTitle,
      article.overview,
      article.whoCanUse,
      article.whereToFind,
      ...(article.beforeYouStart || []),
      ...(article.steps || []),
      ...(article.commonIssues || []),
      ...(article.related || []),
    ].join(" ").toLowerCase();
    return normalized.split(/\s+/).every((term) => haystack.includes(term));
  });
};
