import api from './axios'

export const crmApi = {
  getDashboard: () => api.get('/crm/dashboard'),
  getDashboardFollowUps: (params) => api.get('/crm/dashboard/follow-ups', { params }),
  getCompanies: (params) => api.get('/crm/companies', { params }),
  getCompany: (companyId) => api.get(`/crm/companies/${companyId}`),
  createCompany: (payload) => api.post('/crm/companies', payload),
  updateCompany: (companyId, payload) => api.patch(`/crm/companies/${companyId}`, payload),
  deleteCompany: (companyId) => api.delete(`/crm/companies/${companyId}`),
  getPipeline: (params) => api.get('/crm/pipeline', { params }),
  getLeads: (params) => api.get('/crm/leads', { params }),
  updatePipelineStage: (leadId, payload) => api.patch(`/crm/pipeline/${leadId}/stage`, payload),
  updateStageStatus: (leadId, stageStatus) => api.patch(`/crm/pipeline/${leadId}/status`, { stage_status: stageStatus }),
  bulkAssignLeads: (payload) => api.post('/crm/pipeline/bulk-assign', payload),
  bulkDeleteLeads: (leadIds) => api.post('/crm/pipeline/bulk-delete', { lead_ids: leadIds }),
  // suppressGlobalToast so the axios interceptor doesn't double-toast; the page
  // shows its own toast for delete failures.
  deleteLead: (leadId) => api.delete(`/crm/pipeline/${leadId}`, { suppressGlobalToast: true }),
  restoreLead: (leadId, restoreToken) => api.post(`/crm/pipeline/${leadId}/restore`, { restore_token: restoreToken }),
  updateLeadConversion: (leadId, payload) => api.patch(`/crm/pipeline/${leadId}/conversion`, payload),
  transferLeadToClients: (leadId) => api.post(`/crm/pipeline/${leadId}/transfer`),
  getPipelineHistory: (leadId) => api.get(`/crm/pipeline/history/${leadId}`),
  getDuplicateProspects: (params) => api.get('/crm/duplicates', { params }),
  getLeadTimeline: (leadId) => api.get(`/crm/leads/${leadId}/timeline`),
  getActivities: (params) => api.get('/crm/activities', { params }),
  createActivity: (payload) => api.post('/crm/activities', payload),
  updateActivity: (activityId, payload) => api.patch(`/crm/activities/${activityId}`, payload),
  deleteActivity: (activityId) => api.delete(`/crm/activities/${activityId}`),
  getLeadDeal: (leadId) => api.get(`/crm/leads/${leadId}/deal`),
  updateLeadDeal: (leadId, payload) => api.patch(`/crm/leads/${leadId}/deal`, payload),
  getLeadProposals: (leadId) => api.get(`/crm/leads/${leadId}/proposals`),
  createLeadProposal: (leadId, payload) => api.post(`/crm/leads/${leadId}/proposals`, payload),
  updateLeadProposal: (leadId, proposalId, payload) => api.patch(`/crm/leads/${leadId}/proposals/${proposalId}`, payload),
  archiveLeadProposal: (leadId, proposalId) => api.post(`/crm/leads/${leadId}/proposals/${proposalId}/archive`),
  getLeadDocuments: (leadId) => api.get(`/crm/leads/${leadId}/documents`),
  getLeadDiscovery: (leadId) => api.get(`/crm/leads/${leadId}/discovery`),
  updateLeadDiscovery: (leadId, payload) => api.patch(`/crm/leads/${leadId}/discovery`, payload),
  completeLeadDiscovery: (leadId) => api.post(`/crm/leads/${leadId}/discovery/complete`),
  getLeadAudit: (leadId) => api.get(`/crm/leads/${leadId}/audit`),
  updateLeadAudit: (leadId, payload) => api.patch(`/crm/leads/${leadId}/audit`, payload),
  completeLeadAudit: (leadId) => api.post(`/crm/leads/${leadId}/audit/complete`),
  getLeadNegotiation: (leadId) => api.get(`/crm/leads/${leadId}/negotiation`),
  updateLeadNegotiation: (leadId, payload) => api.patch(`/crm/leads/${leadId}/negotiation`, payload),
  generateQuotationFromDiscoveryAudit: (leadId) => api.post(`/crm/leads/${leadId}/quotation-drafts/from-discovery-audit`),
  createLeadDocument: (leadId, payload) => api.post(`/crm/leads/${leadId}/documents`, payload),
  updateLeadDocument: (leadId, documentId, payload) => api.patch(`/crm/leads/${leadId}/documents/${documentId}`, payload),
  generateLeadDocumentPdf: (leadId, documentId) => api.post(`/crm/leads/${leadId}/documents/${documentId}/generate-pdf`),
  downloadLeadDocumentPdf: (leadId, documentId) => api.get(`/crm/leads/${leadId}/documents/${documentId}/pdf`, { responseType: 'blob' }),
  sendLeadDocument: (leadId, documentId, payload) => api.post(`/crm/leads/${leadId}/documents/${documentId}/send`, payload),
  createLeadDocumentShareLink: (leadId, documentId, payload) => api.post(`/crm/leads/${leadId}/documents/${documentId}/share-link`, payload),
  revokeLeadDocumentShareLink: (leadId, documentId) => api.post(`/crm/leads/${leadId}/documents/${documentId}/revoke-link`),
  cancelLeadDocument: (leadId, documentId) => api.post(`/crm/leads/${leadId}/documents/${documentId}/cancel`),
  createContractFromDocument: (leadId, documentId) => api.post(`/crm/leads/${leadId}/documents/${documentId}/create-contract`),
  uploadLeadDocumentPdf: (leadId, payload) => api.post(`/crm/leads/${leadId}/documents/upload`, payload),
  leadDocumentPdfUrl: (leadId, documentId) => `/api/v1/crm/leads/${leadId}/documents/${documentId}/pdf`,
  getLeadFiles: (leadId) => api.get(`/crm/leads/${leadId}/files`),
  uploadLeadFile: (leadId, payload) => api.post(`/crm/leads/${leadId}/files`, payload),
  deleteLeadFile: (leadId, fileId) => api.delete(`/crm/leads/${leadId}/files/${fileId}`),
  getLeadNotes: (leadId) => api.get(`/crm/leads/${leadId}/notes`),
  createLeadNote: (leadId, payload) => api.post(`/crm/leads/${leadId}/notes`, payload),
  updateLeadNote: (leadId, noteId, payload) => api.patch(`/crm/leads/${leadId}/notes/${noteId}`, payload),
  deleteLeadNote: (leadId, noteId) => api.delete(`/crm/leads/${leadId}/notes/${noteId}`),
  getContacts: (params) => api.get('/crm/contacts', { params }),
  getContact: (contactId) => api.get(`/crm/contacts/${contactId}`),
  createContact: (payload) => api.post('/crm/contacts', payload),
  updateContact: (contactId, payload) => api.patch(`/crm/contacts/${contactId}`, payload),
  deleteContact: (contactId) => api.delete(`/crm/contacts/${contactId}`),
}

export const publicCrmDocumentsApi = {
  getDocument: (token) => api.get(`/public/crm-documents/${token}`, { skipAuth: true, allowUnauthenticated: true }),
  downloadPdf: (token) => api.get(`/public/crm-documents/${token}/pdf`, { responseType: 'blob', skipAuth: true, allowUnauthenticated: true }),
  accept: (token, payload) => api.post(`/public/crm-documents/${token}/accept`, payload, { skipAuth: true, allowUnauthenticated: true }),
  reject: (token, payload) => api.post(`/public/crm-documents/${token}/reject`, payload, { skipAuth: true, allowUnauthenticated: true }),
  requestChanges: (token, payload) => api.post(`/public/crm-documents/${token}/request-changes`, payload, { skipAuth: true, allowUnauthenticated: true }),
  pdfUrl: (token) => `/api/v1/public/crm-documents/${token}/pdf`,
}
