import api from './axios'

export const superadminApi = {
  getTenants: (params) => api.get('/superadmin/tenants/', { params }),
  getTenant: (id) => api.get(`/superadmin/tenants/${id}`),
  getCompanyUsers: (companyId) => api.get(`/superadmin/tenants/${companyId}/users`),
  resetUserPassword: (companyId, userId) => api.post(`/superadmin/tenants/${companyId}/users/${userId}/reset-password`),
  approveTenant: (id) => api.post(`/superadmin/tenants/${id}/approve`),
  suspendTenant: (id, data) => api.post(`/superadmin/tenants/${id}/suspend`, data),
  activateTenant: (id) => api.post(`/superadmin/tenants/${id}/activate`),
  assignPlan: (companyId, data) => api.post(`/superadmin/tenants/${companyId}/assign-plan`, data),
  getSubscriptionOverview: () => api.get('/superadmin/tenants/subscription-overview'),
  updateTenantModules: (id, data) => api.put(`/superadmin/tenants/${id}/modules`, data),
  updateTenantSubscription: (id, data) => api.put(`/superadmin/tenants/${id}/subscription`, data),
  getPlans: () => api.get('/superadmin/plans/'),
  getPlan: (id) => api.get(`/superadmin/plans/${id}`),
  createPlan: (data) => api.post('/superadmin/plans/', data),
  updatePlan: (id, data) => api.put(`/superadmin/plans/${id}`, data),
  deletePlan: (id) => api.delete(`/superadmin/plans/${id}`),
  getUsageAnalytics: (params) => api.get('/superadmin/usage/analytics', { params }),
  getCompanyUsage: (id) => api.get(`/superadmin/usage/company/${id}`),
  getCompanyDetailedUsage: (id) => api.get(`/superadmin/usage/company/${id}/detailed`),
  getAllCompaniesUsageSummary: () => api.get('/superadmin/usage/all-companies-summary'),
  getTransactions: (params) => api.get('/superadmin/billing/transactions', { params }),
  getRevenueAnalytics: (params) => api.get('/superadmin/billing/revenue/analytics', { params }),
  generateInvoice: (data) => api.post('/superadmin/billing/invoices/generate', data),
  sendInvoice: (invoiceId) => api.post(`/superadmin/billing/invoices/${invoiceId}/send`),
  listInvoices: (params) => api.get('/superadmin/billing/invoices', { params }),
  getAvailableFeatures: () => api.get('/superadmin/features/available'),
  getCompanyFeatures: (companyId) => api.get(`/superadmin/features/${companyId}`),
  toggleFeature: (companyId, data) => api.put(`/superadmin/features/${companyId}/toggle`, data),
}
